### ISSUE TITLE
Add ipwhitelist filter

### ISSUE THREAD

**Issue by Keltere** [pathwae/proxy#2]
A simple request to add ipwhitelist as a filter

**Comment by metal3d** [comment]
That's a feature that nesds a few more information.

What do you think of declaring this way:
```yaml
foo.localhost:
    to: container1:3030
    allow:
        /this/path: 10.1.2.3,10.1.2.4
```
